version: "3.9"

services:
  postgres:
    build: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sqldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres:/postgres

    entrypoint: ["/postgres/entrypoint.sh"]

  api:
    build: ./api
    container_name: fastapi_api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: sqldb
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - ./api:/app

volumes:
  postgres_data: